# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
# DEBUG BASH SCRIPT
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: ls
# DOCKER BUILD
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

# Docker PUSH
    - task: Docker@2
      inputs:
        command: 'push'